CREATE EXTENSION postgis;

CREATE TABLE clientes (
  nome VARCHAR(100) NOT NULL,
  cnpj VARCHAR(14) UNIQUE NOT NULL PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  uf VARCHAR(2) NOT NULL,
  localizacao GEOGRAPHY(POINT, 4326) NOT NULL
);